"""Adiciona progresso de leitura para livros da comunidade

Revision ID: 6e2b59396243
Revises: f9f6ad08e073
Create Date: 2025-07-20 11:30:02.708034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e2b59396243'
down_revision = 'f9f6ad08e073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_community_book_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('community_book_id', sa.Integer(), nullable=False),
    sa.Column('current_page', sa.Integer(), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('last_read_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['community_book_id'], ['community_book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'community_book_id', name='_user_community_book_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_community_book_progress')
    # ### end Alembic commands ###
